import { useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDownLeft, ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronDown, Copy, CreditCard, ExternalLink, FileText, LayoutDashboard, Link2, Loader2, LogOut, Mail, MoreHorizontal, Plus, Printer, Search, Settings, ShieldCheck, Sparkles, Trash2, X } from 'lucide-react';
import Landing from './Landing';
import Billing from './Billing';
import PriceHelper from './PriceHelper';
import QuoteDocument, { frequencyLabels, lineAmount, totals } from './QuoteDocument';
import { api, dateLabel, errorMessage, money } from './api';
import type { Business, Frequency, Quote, QuoteInput, Usage, User } from './types';

type View = 'dashboard' | 'editor' | 'settings' | 'billing';
type Toast = { message: string; error?: boolean };
const emptyDraft = (currency = 'TRY'): QuoteInput => ({ title: 'Home cleaning quote', clientName: '', clientEmail: '', address: '', frequency: 'one-time', items: templateItems(0, currency), discountPercent: 0, taxPercent: 0, notes: 'All cleaning supplies included. Please let us know about access arrangements or special requests before your visit.', validUntil: new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10) });
const templates = [
  { name: 'Standard clean', detail: 'A regular refresh', title: 'Home cleaning quote', items: [{ name: 'Standard home cleaning', description: 'Kitchen, bathrooms, bedrooms, and living areas', quantity: 1, unitPrice: 180000 }] },
  { name: 'Deep clean', detail: 'Top to bottom', title: 'Deep cleaning quote', items: [{ name: 'Deep home cleaning', description: 'Detailed cleaning of kitchens, bathrooms, surfaces, and floors', quantity: 1, unitPrice: 3200000 }, { name: 'Inside oven cleaning', description: 'Degrease and detail the oven interior', quantity: 1, unitPrice: 35000 }] },
  { name: 'Move-out clean', detail: 'Ready for what’s next', title: 'Move-out cleaning quote', items: [{ name: 'Move-out cleaning', description: 'Thorough cleaning of an empty property, including cabinets', quantity: 1, unitPrice: 320000 }, { name: 'Inside refrigerator cleaning', description: 'Clean and sanitize shelves and drawers', quantity: 1, unitPrice: 35000 }] },
];
const illustrativePrices: Record<string, number[][]> = {
  TRY: [[180000], [280000, 35000], [320000, 35000]],
  USD: [[12000], [24000, 3500], [28000, 2500]],
  EUR: [[11000], [22000, 3000], [26000, 2500]],
  GBP: [[9500], [18000, 2500], [23000, 2200]],
  CAD: [[16000], [28000, 4500], [34000, 3500]],
  AUD: [[18000], [30000, 4500], [36000, 4000]],
};
function templateItems(index: number, currency: string) {
  return templates[index].items.map((item, itemIndex) => ({ ...item, unitPrice: illustrativePrices[currency]?.[index]?.[itemIndex] ?? 0 }));
}
const businessFromUser = (user: User): Business => ({ name: user.businessName, email: user.businessEmail, phone: user.phone, currency: user.currency });
const publicUrl = (quote: Quote) => `${window.location.origin}/q/${quote.publicToken}`;

function Button({ children, className = '', loading = false, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { loading?: boolean }) {
  return <button className={`btn ${className}`} {...props} disabled={props.disabled || loading}>{loading ? <Loader2 size={17} className="spin" /> : null}{children}</button>;
}
function Logo({ small = false }: { small?: boolean }) { return <span className={`app-logo ${small ? 'small' : ''}`}><span><Sparkles size={small ? 19 : 23} strokeWidth={1.8} /></span>neatquote<span className="logo-dot">.</span></span>; }
function Modal({ title, children, onClose, className = '' }: { title: string; children: ReactNode; onClose: () => void; className?: string }) {
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { dialog.current?.showModal(); }, []);
  return <dialog ref={dialog} className={`modal ${className}`} onCancel={event => { event.preventDefault(); onClose(); }} onClick={event => { if (event.target === event.currentTarget) onClose(); }}><div className="modal-header"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20} /></button></div>{children}</dialog>;
}
function Status({ status }: { status: Quote['status'] }) { return <span className={`status status-${status}`}><span />{status === 'draft' ? 'Draft' : status === 'sent' ? 'Shared' : 'Accepted'}</span>; }

function PreviewNote({ inline = false }: { inline?: boolean }) { return <div className={`preview-note ${inline ? 'preview-note-inline' : ''}`} role="note"><span><strong>Preview</strong> · Use sample data. Accounts and quotes may reset.</span></div>; }

function AuthModal({ mode, onMode, onClose, onAuth, previewMode }: { previewMode: boolean; mode: 'signup' | 'login'; onMode: (mode: 'signup' | 'login') => void; onClose: () => void; onAuth: (user: User) => void }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(''); setBusy(true);
    const form = new FormData(event.currentTarget);
    try { const { user } = await api<{ user: User }>(`/api/auth/${mode}`, { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); onAuth(user); } catch (err) { setError(errorMessage(err)); } finally { setBusy(false); }
  }
  return <Modal title={mode === 'signup' ? 'Make your next quote a neat one.' : 'Welcome back.'} onClose={onClose} className="auth-modal"><p className="muted">{mode === 'signup' ? 'Start with 3 free quotes each month. No card needed.' : 'Let’s get back to growing your cleaning business.'}</p>{previewMode && <PreviewNote inline />}<form onSubmit={submit} className="form-stack">{mode === 'signup' && <><label>Your name<input name="name" autoComplete="name" required maxLength={80} autoFocus placeholder="Alex Morgan" /></label><label>Business name<input name="businessName" autoComplete="organization" required maxLength={100} placeholder="Your cleaning business" /></label></>}<label>Email address<input name="email" type="email" autoComplete="email" required autoFocus={mode === 'login'} placeholder="you@yourbusiness.com" /></label><label>Password<input name="password" type="password" autoComplete={mode === 'signup' ? 'new-password' : 'current-password'} required minLength={mode === 'signup' ? 8 : undefined} maxLength={128} placeholder={mode === 'signup' ? 'At least 8 characters' : 'Your password'} /></label>{error && <p className="form-error" role="alert">{error}</p>}<Button type="submit" className="btn-primary full-width" loading={busy}>{mode === 'signup' ? 'Create my free account' : 'Log in'}<ArrowRight size={16} /></Button></form><p className="auth-switch">{mode === 'signup' ? 'Already have an account?' : 'New to NeatQuote?'} <button onClick={() => { setError(''); onMode(mode === 'signup' ? 'login' : 'signup'); }}>{mode === 'signup' ? 'Log in' : 'Get started free'}</button></p>{mode === 'signup' && <p className="auth-note"><ShieldCheck size={14} />Your account and client quotes stay private.</p>}</Modal>;
}

function PublicQuote({ token, previewMode }: { token: string; previewMode: boolean }) {
  const [data, setData] = useState<{ quote: Quote; business: Business } | null>(null);
  const [error, setError] = useState('');
  const [name, setName] = useState('');
  const [busy, setBusy] = useState(false);
  const [accepted, setAccepted] = useState(false);
  useEffect(() => { let active = true; api<{ quote: Quote; business: Business }>(`/api/public/quotes/${encodeURIComponent(token)}`).then(value => { if (active) { setData(value); setName(value.quote.clientName); setAccepted(value.quote.status === 'accepted'); } }).catch(err => { if (active) setError(errorMessage(err)); }); return () => { active = false; }; }, [token]);
  async function accept(event: FormEvent) { event.preventDefault(); if (!data) return; setBusy(true); setError(''); try { const { quote } = await api<{ quote: Quote }>(`/api/public/quotes/${encodeURIComponent(token)}/accept`, { method: 'POST', body: JSON.stringify({ name }) }); setData({ ...data, quote }); setAccepted(true); } catch (err) { setError(errorMessage(err)); } finally { setBusy(false); } }
  return <div className={`public-page ${previewMode ? 'preview-mode' : ''}`}>{previewMode && <PreviewNote />}<header className="public-header"><a href="/" aria-label="NeatQuote home"><Logo small /></a><span><ShieldCheck size={15} />Your personal cleaning quote</span></header>{!data ? <div className="public-state">{error ? <><FileText size={36} /><h1>This quote is unavailable.</h1><p>{error}</p><a className="btn btn-secondary" href="/">Back to NeatQuote</a></> : <><Loader2 className="spin" size={30} /><p>Getting your quote ready…</p></>}</div> : <><div className="public-toolbar"><p>A cleaner space starts here.</p><Button className="btn-secondary" onClick={() => window.print()}><Printer size={16} />Print / save PDF</Button></div><QuoteDocument quote={data.quote} business={data.business} /><section className={`accept-card ${accepted ? 'accepted-card' : ''}`}>{accepted ? <><CheckCircle2 size={32} /><h2>You’re all set.</h2><p>Your quote has been accepted. {data.business.name} can now follow up to arrange your cleaning.</p>{data.business.email && <a href={`mailto:${data.business.email}`}><Mail size={15} />Contact {data.business.name}</a>}</> : <><div><span className="eyebrow">READY FOR A FRESH START?</span><h2>Looks good? Let’s make it happen.</h2><p>Accepting confirms your interest and agreement to this quote. Your cleaning business will arrange the visit. No payment is taken here.</p></div><form onSubmit={accept}><label>Your full name<input required value={name} onChange={event => setName(event.target.value)} maxLength={100} autoComplete="name" /></label><Button type="submit" className="btn-primary" loading={busy}><Check size={17} />Accept quote</Button></form></>}{error && <p role="alert" className="form-error">{error}</p>}</section><p className="public-credit">A little more polished, with <a href="/">NeatQuote</a>.</p></>}</div>;
}

function Dashboard({ user, quotes, usage, loading, error, refresh, onCreate, onEdit, onDelete, onUpgrade }: { user: User; quotes: Quote[]; usage: Usage | null; loading: boolean; error: string; refresh: () => void; onCreate: () => void; onEdit: (quote: Quote) => void; onDelete: (quote: Quote) => void; onUpgrade: () => void }) {
  const [filter, setFilter] = useState('all');
  const [search, setSearch] = useState('');
  const accepted = quotes.filter(quote => quote.status === 'accepted');
  const acceptedTotals = accepted.reduce<Record<string, number>>((values, quote) => { const currency = quote.currency || user.currency; values[currency] = (values[currency] || 0) + quote.total; return values; }, {});
  const shared = quotes.filter(quote => quote.status === 'sent');
  const visible = quotes.filter(quote => (filter === 'all' || quote.status === filter) && `${quote.title} ${quote.clientName} ${quote.clientEmail}`.toLowerCase().includes(search.toLowerCase()));
  const limitReached = user.plan === 'free' && usage?.limit !== null && usage !== null && usage.used >= usage.limit;
  return <div className="dashboard-content"><div className="page-heading"><div><p className="eyebrow">A LITTLE ORDER. A LOT OF POSSIBILITY.</p><h1>Your business, looking sharp.</h1><p className="muted">Welcome back, {user.name.split(' ')[0]}. Let’s turn the next inquiry into a yes.</p></div><Button className="btn-primary" onClick={limitReached ? onUpgrade : onCreate}><Plus size={17} />{limitReached ? 'Explore Pro' : 'New quote'}</Button></div>
    <div className="metrics-grid"><div className="metric-card"><div className="metric-top"><span>Total quotes</span><span className="metric-icon mint"><FileText size={19} /></span></div><strong>{quotes.length}</strong><p>Your work, beautifully presented</p></div><div className="metric-card"><div className="metric-top"><span>Awaiting a yes</span><span className="metric-icon peach"><ArrowDownLeft size={20} /></span></div><strong>{shared.length}</strong><p>Shared quotes ready for follow-up</p></div><div className="metric-card"><div className="metric-top"><span>Accepted quote value</span><span className="metric-icon green"><CheckCircle2 size={19} /></span></div><strong className="metric-money">{Object.keys(acceptedTotals).length > 1 ? `${accepted.length} quotes` : money(Object.values(acceptedTotals)[0] || 0, Object.keys(acceptedTotals)[0] || user.currency)}</strong><p>{Object.keys(acceptedTotals).length > 1 ? Object.entries(acceptedTotals).map(([code, value]) => `${money(value, code)} ${code}`).join(' + ') : `${accepted.length} accepted ${accepted.length === 1 ? 'quote' : 'quotes'} · payment tracked separately`}</p></div></div>
    <section className="quotes-panel"><div className="panel-heading"><div><h2>Your quotes <span className="count-bubble">{quotes.length}</span></h2><p>A tidy home for every opportunity.</p></div><div className="search-field"><Search size={17} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search client or quote…" aria-label="Search quotes" /></div></div><div className="quote-filters" role="tablist" aria-label="Quote status">{[['all', 'All quotes'], ['draft', 'Drafts'], ['sent', 'Shared'], ['accepted', 'Accepted']].map(([value, label]) => <button key={value} role="tab" aria-selected={filter === value} className={filter === value ? 'active' : ''} onClick={() => setFilter(value)}>{label}<span>{value === 'all' ? quotes.length : quotes.filter(quote => quote.status === value).length}</span></button>)}</div>
    {error ? <div className="empty-state"><p role="alert" className="form-error">{error}</p><Button className="btn-secondary" onClick={refresh}>Try again</Button></div> : loading ? <div className="empty-state"><Loader2 size={27} className="spin" /><p>Loading your quotes…</p></div> : visible.length === 0 ? <div className="empty-state"><div className="empty-illustration"><FileText size={37} strokeWidth={1.3} /><span><Sparkles size={16} /></span></div><h3>{quotes.length ? 'No quotes found.' : 'Your next client starts here.'}</h3><p>{quotes.length ? 'Try another search or status filter.' : 'Create a clear, professional quote in minutes. Then share the link and let your client say yes.'}</p>{!quotes.length && <Button className="btn-primary" onClick={limitReached ? onUpgrade : onCreate}><Plus size={16} />{limitReached ? 'Explore Pro' : 'Create your first quote'}</Button>}</div> : <div className="quote-table-wrap"><table className="quote-table"><thead><tr><th>Client / quote</th><th>Created</th><th>Status</th><th>Amount</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{visible.map(quote => <tr key={quote.id}><td><button className="quote-name" onClick={() => onEdit(quote)}><strong>{quote.clientName}</strong><span>{quote.title}</span></button></td><td className="table-date">{dateLabel(quote.createdAt)}</td><td><Status status={quote.status} /></td><td className="table-amount">{money(quote.total, quote.currency || user.currency)}{(quote.frequency !== 'one-time' || (quote.currency && quote.currency !== user.currency)) && <span>{[quote.currency && quote.currency !== user.currency ? quote.currency : '', quote.frequency !== 'one-time' ? 'per visit' : ''].filter(Boolean).join(' · ')}</span>}</td><td><div className="row-actions"><button className="icon-button" aria-label={`Open quote for ${quote.clientName}`} onClick={() => onEdit(quote)}><ArrowRight size={17} /></button>{quote.status !== 'accepted' && <button className="icon-button delete-button" aria-label={`Delete quote for ${quote.clientName}`} onClick={() => onDelete(quote)}><Trash2 size={16} /></button>}</div></td></tr>)}</tbody></table></div>}</section>
    <div className="dashboard-tip"><span><Sparkles size={21} /></span><div><strong>A small detail that makes a big difference.</strong><p>Add a personal note to your quote. Clear expectations and a warm welcome go a long way.</p></div></div>
  </div>;
}

function QuoteEditor({ user, initial, onBack, onSaved, notify }: { user: User; initial: Quote | null; onBack: () => void; onSaved: (quote: Quote) => void; notify: (message: string, error?: boolean) => void }) {
  const [draft, setDraft] = useState<QuoteInput>(initial || emptyDraft(user.currency));
  const [saved, setSaved] = useState<Quote | null>(initial);
  const [busy, setBusy] = useState<'save' | 'share' | null>(null);
  const [preview, setPreview] = useState(false);
  const [dirty, setDirty] = useState(!initial);
  const [error, setError] = useState('');
  const accepted = saved?.status === 'accepted';
  const currency = initial?.currency || user.currency;
  const calculated = totals(draft);
  const form = useRef<HTMLFormElement>(null);
  function patch(changes: Partial<QuoteInput>) { setDraft(value => ({ ...value, ...changes })); setDirty(true); }
  function itemPatch(index: number, changes: Partial<QuoteInput['items'][number]>) { setDraft(value => ({ ...value, items: value.items.map((item, itemIndex) => itemIndex === index ? { ...item, ...changes } : item) })); setDirty(true); }
  async function save(share = false) {
    if (!form.current?.reportValidity()) return;
    setBusy(share ? 'share' : 'save'); setError('');
    try {
      let quote = saved;
      if (!quote || dirty) {
        const payload: QuoteInput = { title: draft.title, clientName: draft.clientName, clientEmail: draft.clientEmail, address: draft.address, frequency: draft.frequency, items: draft.items, discountPercent: draft.discountPercent, taxPercent: draft.taxPercent, notes: draft.notes, validUntil: draft.validUntil };
        const result = await api<{ quote: Quote }>(saved ? `/api/quotes/${saved.id}` : '/api/quotes', { method: saved ? 'PUT' : 'POST', body: JSON.stringify(payload) }); quote = result.quote;
      }
      if (share) { const result = await api<{ quote: Quote }>(`/api/quotes/${quote.id}/send`, { method: 'POST' }); quote = result.quote; }
      setSaved(quote); setDraft(quote); setDirty(false); onSaved(quote); notify(share ? 'Your share link is ready. Copy it and send it to your client.' : 'Quote saved. Looking good!');
    } catch (err) { setError(errorMessage(err)); } finally { setBusy(null); }
  }
  async function copy(value: string, message: string) { try { await navigator.clipboard.writeText(value); notify(message); } catch { notify('Clipboard access isn’t available. Select and copy the link below.', true); } }
  function back() { if (!dirty || window.confirm('Leave without saving your changes?')) onBack(); }
  return <div className="editor-page"><div className="editor-heading"><div><button className="back-link" onClick={back}><ArrowLeft size={15} />All quotes</button><h1>{initial ? accepted ? 'A happy yes.' : 'Make it a neat quote.' : 'One step closer to a yes.'}</h1><p className="muted">{accepted ? 'Your client accepted this quote. These details are now locked.' : 'The details are yours. We’ll take care of the polish.'}</p></div><div className="editor-actions"><Button className="btn-secondary" onClick={() => setPreview(true)}><ExternalLink size={16} />Preview</Button>{!accepted && <Button className="btn-secondary" loading={busy === 'save'} disabled={!!busy || !dirty} onClick={() => save()}>Save draft</Button>}{!accepted && <Button className="btn-primary" loading={busy === 'share'} disabled={!!busy} onClick={() => save(true)}><Link2 size={16} />{saved?.status === 'sent' ? 'Update share link' : 'Create share link'}</Button>}</div></div>{error && <p className="form-error editor-error" role="alert">{error}</p>}
    {saved && saved.status !== 'draft' && <div className="share-banner"><span className="share-icon"><Link2 size={21} /></span><div><strong>{accepted ? 'Quote accepted' : 'Ready to share with your client'}</strong><p>{accepted ? `${saved.acceptedName} accepted on ${dateLabel(saved.acceptedAt || saved.updatedAt)}.` : dirty ? 'Your link shows the last saved version. Save your changes before sharing.' : 'Copy the link and send it by email, text, or WhatsApp.'}</p><input className="share-link-input" aria-label="Client quote link" readOnly value={publicUrl(saved)} onFocus={event => event.target.select()} /></div><Button className="btn-secondary" onClick={() => copy(publicUrl(saved), 'Quote link copied.')}><Copy size={16} />Copy link</Button>{!accepted && <Button className="btn-text" onClick={() => copy(`Hi ${draft.clientName.split(' ')[0]}, thanks for considering ${user.businessName}! Here’s your cleaning quote: ${publicUrl(saved)}. You can review the details and accept right there. Happy to answer any questions.`, 'Personal follow-up copied. Paste it into your email or message.')}><Mail size={16} />Copy message</Button>}</div>}
    <div className="editor-layout"><form ref={form} className="editor-form" onSubmit={event => { event.preventDefault(); save(); }}><fieldset disabled={accepted}><section className="form-card"><div className="section-heading"><span className="step-number">01</span><div><h2>The right starting point</h2><p>Pick a template, then make the prices your own.</p></div></div><div className="template-grid">{templates.map(template => <button type="button" key={template.name} className="template-card" onClick={() => patch({ title: template.title, items: templateItems(templates.indexOf(template), currency) })}><Sparkles size={18} /><strong>{template.name}</strong><span>{template.detail}</span></button>)}</div><p className="field-help">Template prices are examples, not market rates. Set your own prices for your time, costs, and scope.</p><label>Quote title<input required value={draft.title} onChange={event => patch({ title: event.target.value })} maxLength={150} placeholder="Home cleaning quote" /></label></section>
    <section className="form-card"><div className="section-heading"><span className="step-number">02</span><div><h2>Who are we cleaning for?</h2><p>A few details to make it personal.</p></div></div><div className="form-two-columns"><label>Client name<input required value={draft.clientName} onChange={event => patch({ clientName: event.target.value })} maxLength={100} placeholder="Jamie Taylor" /></label><label>Client email <span className="optional">optional</span><input type="email" value={draft.clientEmail} onChange={event => patch({ clientEmail: event.target.value })} maxLength={254} placeholder="jamie@email.com" /></label></div><label>Property address <span className="optional">optional</span><input value={draft.address} onChange={event => patch({ address: event.target.value })} maxLength={300} placeholder="Street address, city" /></label><div className="form-two-columns"><label>Cleaning frequency<select value={draft.frequency} onChange={event => patch({ frequency: event.target.value as Frequency })}>{Object.entries(frequencyLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Quote valid until<input type="date" required value={draft.validUntil} onChange={event => patch({ validUntil: event.target.value })} /></label></div></section>
    <section className="form-card"><div className="section-heading"><span className="step-number">03</span><div><h2>A clear price for a clean space</h2><p>Spell out what’s included. No surprises.</p></div></div><div className="line-items">{draft.items.map((item, index) => <div className="line-item" key={index}><div className="line-item-heading"><span>Service {index + 1}</span><button type="button" className="icon-button delete-button" disabled={draft.items.length === 1} aria-label={`Remove service ${index + 1}`} onClick={() => patch({ items: draft.items.filter((_, itemIndex) => itemIndex !== index) })}><Trash2 size={15} /></button></div><label>Service name<input required value={item.name} onChange={event => itemPatch(index, { name: event.target.value })} maxLength={120} placeholder="Standard home cleaning" /></label><label>Description <span className="optional">optional</span><input value={item.description} onChange={event => itemPatch(index, { description: event.target.value })} maxLength={500} placeholder="What’s included?" /></label><div className="line-item-numbers"><label>Quantity<input type="number" required min="0.01" max="10000" step="0.01" value={item.quantity || ''} onChange={event => itemPatch(index, { quantity: Number(event.target.value) })} /></label><label>Unit price ({currency})<input type="number" required min="0" max="100000" step="0.01" value={item.unitPrice / 100} onChange={event => itemPatch(index, { unitPrice: Math.round(Number(event.target.value) * 100) })} /></label><div className="line-total"><span>Amount</span><strong>{money(lineAmount(item.quantity, item.unitPrice), currency)}</strong></div></div></div>)}</div><Button className="btn-secondary add-service" type="button" disabled={draft.items.length >= 30} onClick={() => patch({ items: [...draft.items, { name: '', description: '', quantity: 1, unitPrice: 0 }] })}><Plus size={16} />Add another service</Button><div className="form-two-columns"><label>Discount (%)<input type="number" required min="0" max="100" step="0.01" value={draft.discountPercent} onChange={event => patch({ discountPercent: Number(event.target.value) })} /></label><label>Tax (%)<input type="number" required min="0" max="100" step="0.01" value={draft.taxPercent} onChange={event => patch({ taxPercent: Number(event.target.value) })} /></label></div><p className="field-help">Set the tax that applies to your business. Tax is calculated after any discount.</p></section>
    <PriceHelper currency={currency} disabled={!!accepted} onUse={price => { patch({ items: [{ name: draft.title || 'Cleaning service', description: draft.items.map(item => `${item.name}${item.description ? `: ${item.description}` : ''}`).join('; ').slice(0, 900), quantity: 1, unitPrice: price }] }); notify('Suggested price applied. Review your quote before sharing.'); }} /><section className="form-card"><div className="section-heading"><span className="step-number">04</span><div><h2>The little details</h2><p>Set expectations and add a personal touch.</p></div></div><label>Notes for your client <span className="optional">optional</span><textarea rows={4} value={draft.notes} maxLength={3000} onChange={event => patch({ notes: event.target.value })} placeholder="Supplies, access, scheduling, or a friendly thank you…" /></label></section></fieldset></form>
    <aside className="editor-summary"><div className="summary-card"><span className="eyebrow">YOUR QUOTE AT A GLANCE</span><div className="summary-icon"><Sparkles size={28} strokeWidth={1.4} /></div><h2>{draft.title || 'Your cleaning quote'}</h2><p>{draft.clientName ? `For ${draft.clientName}` : 'A clean slate. A great first impression.'}</p><div className="summary-lines"><div><span>Subtotal</span><strong>{money(calculated.subtotal, currency)}</strong></div>{draft.discountPercent > 0 && <div><span>Discount ({draft.discountPercent}%)</span><strong>−{money(calculated.discount, currency)}</strong></div>}{draft.taxPercent > 0 && <div><span>Tax ({draft.taxPercent}%)</span><strong>{money(calculated.tax, currency)}</strong></div>}</div><div className="summary-total"><span>{draft.frequency === 'one-time' ? 'Quote total' : 'Total per visit'}</span><strong>{money(calculated.total, currency)}</strong></div><div className="summary-detail"><Check size={15} />{frequencyLabels[draft.frequency]}</div><div className="summary-detail"><Check size={15} />{draft.validUntil ? `Valid until ${dateLabel(draft.validUntil)}` : 'Choose a validity date'}</div>{saved && <div className="summary-status"><Status status={saved.status} /></div>}</div><div className="summary-tip"><ShieldCheck size={20} /><p>Share a personal link. Your client can review and accept from any device.</p></div></aside></div>
    {preview && <Modal title="A first look at your quote" onClose={() => setPreview(false)} className="preview-modal"><div className="preview-toolbar"><span>This is how your client will see it.</span><Button className="btn-secondary" onClick={() => window.print()}><Printer size={16} />Print / save PDF</Button></div><QuoteDocument quote={accepted && saved ? saved : draft} business={{ ...businessFromUser(user), currency }} /></Modal>}
  </div>;
}

function ProfileSettings({ user, onUpdated, notify }: { user: User; onUpdated: (user: User) => void; notify: (message: string, error?: boolean) => void }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget); try { const data = await api<{ user: User }>('/api/profile', { method: 'PUT', body: JSON.stringify(Object.fromEntries(form)) }); onUpdated(data.user); notify('Business details updated.'); } catch (err) { setError(errorMessage(err)); } finally { setBusy(false); } }
  return <div className="settings-page"><div className="page-heading"><div><p className="eyebrow">THE FACE OF YOUR BUSINESS</p><h1>Make it yours.</h1><p className="muted">Your details appear on every client quote.</p></div></div><form className="form-card settings-form" onSubmit={save}><h2>Business details</h2><p className="muted">A familiar name. A clear way to get in touch.</p><div className="form-two-columns"><label>Your name<input name="name" required defaultValue={user.name} maxLength={80} autoComplete="name" /></label><label>Business name<input name="businessName" required defaultValue={user.businessName} maxLength={100} autoComplete="organization" /></label></div><div className="form-two-columns"><label>Business email<input name="businessEmail" type="email" defaultValue={user.businessEmail} maxLength={254} autoComplete="email" /></label><label>Business phone <span className="optional">optional</span><input name="phone" type="tel" defaultValue={user.phone} maxLength={50} autoComplete="tel" /></label></div><label>Quote currency<select name="currency" defaultValue={user.currency}><option value="USD">USD — US Dollar</option><option value="TRY">TRY — Turkish Lira</option><option value="EUR">EUR — Euro</option><option value="GBP">GBP — British Pound</option><option value="CAD">CAD — Canadian Dollar</option><option value="AUD">AUD — Australian Dollar</option>{!['USD', 'TRY', 'EUR', 'GBP', 'CAD', 'AUD'].includes(user.currency) && <option value={user.currency}>{user.currency}</option>}</select></label><p className="field-help">Used for new quotes. Existing quotes keep their currency and prices.</p><div className="account-email"><Mail size={17} /><div><strong>Account email</strong><p>{user.email}</p></div></div>{error && <p className="form-error" role="alert">{error}</p>}<Button type="submit" className="btn-primary" loading={busy}>Save changes<Check size={16} /></Button></form></div>;
}
export default function App() {
  const publicMatch = window.location.pathname.match(/^\/q\/([^/]+)\/?$/);
  const [user, setUser] = useState<User | null>(null);
  const [booting, setBooting] = useState(!publicMatch);
  const [authMode, setAuthMode] = useState<'signup' | 'login' | null>(null);
  const [view, setView] = useState<View>(new URLSearchParams(window.location.search).has('payment') ? 'billing' : 'dashboard');
  const [selected, setSelected] = useState<Quote | null>(null);
  const [editorKey, setEditorKey] = useState(0);
  const [quotes, setQuotes] = useState<Quote[]>([]);
  const [usage, setUsage] = useState<Usage | null>(null);
  const [loading, setLoading] = useState(false);
  const [quotesError, setQuotesError] = useState('');
  const [billingEnabled, setBillingEnabled] = useState(false);
  const [previewMode, setPreviewMode] = useState(false);
  const [toast, setToast] = useState<Toast | null>(null);
  const [deleting, setDeleting] = useState<Quote | null>(null);
  const [deleteBusy, setDeleteBusy] = useState(false);
  const notify = useCallback((message: string, error = false) => setToast({ message, error }), []);
  const refresh = useCallback(async () => { setLoading(true); setQuotesError(''); try { const result = await api<{ quotes: Quote[]; usage: Usage }>('/api/quotes'); setQuotes(result.quotes); setUsage(result.usage); } catch (err) { setQuotesError(errorMessage(err)); } finally { setLoading(false); } }, []);
  useEffect(() => {
    let active = true;
    Promise.allSettled([
      publicMatch ? Promise.resolve(null) : api<{ user: User }>('/api/auth/me'),
      api<{ ok: boolean; billingEnabled: boolean; previewMode?: boolean }>('/api/health'),
    ]).then(([auth, health]) => {
      if (!active) return;
      if (auth.status === 'fulfilled' && auth.value) setUser(auth.value.user);
      if (health.status === 'fulfilled') { setBillingEnabled(health.value.billingEnabled); setPreviewMode(health.value.previewMode === true); }
      setBooting(false);
    });
    return () => { active = false; };
  }, []);
  useEffect(() => { if (user) refresh(); }, [user?.id, user?.plan, refresh]);
  useEffect(() => { if (!user) return; const recheck = () => { api<{ user: User }>('/api/auth/me').then(data => setUser(data.user)).catch(() => {}); refresh(); }; window.addEventListener('focus', recheck); return () => window.removeEventListener('focus', recheck); }, [user?.id, refresh]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(null), 6500); return () => window.clearTimeout(timer); }, [toast]);
  useEffect(() => { if (!user || new URLSearchParams(window.location.search).get('payment') !== 'success') return; const timer = window.setInterval(() => { api<{ user: User }>('/api/auth/me').then(data => setUser(data.user)).catch(() => {}); }, 3000); const stop = window.setTimeout(() => window.clearInterval(timer), 30000); return () => { window.clearInterval(timer); window.clearTimeout(stop); }; }, [user?.id]);
  function openEditor(quote: Quote | null) { setSelected(quote); setEditorKey(value => value + 1); setView('editor'); window.scrollTo(0, 0); }
  function saved(quote: Quote) { setQuotes(values => [quote, ...values.filter(value => value.id !== quote.id)].sort((a, b) => b.createdAt.localeCompare(a.createdAt))); setSelected(quote); refresh(); }
  async function logout() { try { await api('/api/auth/logout', { method: 'POST' }); setUser(null); setQuotes([]); setUsage(null); setView('dashboard'); } catch (err) { notify(errorMessage(err), true); } }
  async function remove() { if (!deleting) return; setDeleteBusy(true); try { await api(`/api/quotes/${deleting.id}`, { method: 'DELETE' }); setQuotes(values => values.filter(quote => quote.id !== deleting.id)); setDeleting(null); notify('Quote deleted.'); } catch (err) { notify(errorMessage(err), true); } finally { setDeleteBusy(false); } }
  if (publicMatch) return <PublicQuote token={publicMatch[1]} previewMode={previewMode} />;
  if (booting) return <div className="boot-screen"><Logo /><Loader2 className="spin" size={24} /><p>A little polish, coming right up…</p></div>;
  if (!user) return <>{previewMode && !authMode && <PreviewNote />}<Landing onStart={() => setAuthMode('signup')} onLogin={() => setAuthMode('login')} />{authMode && <AuthModal previewMode={previewMode} mode={authMode} onMode={setAuthMode} onClose={() => setAuthMode(null)} onAuth={value => { setUser(value); setAuthMode(null); }} />}</>;
  return <div className={`app-shell ${previewMode ? 'preview-mode' : ''}`}>{previewMode && <PreviewNote />}<aside className="sidebar"><button className="logo-button" onClick={() => setView('dashboard')} aria-label="NeatQuote dashboard"><Logo /></button><div className="sidebar-business"><span>{user.businessName.slice(0, 1).toUpperCase()}</span><div><strong>{user.businessName}</strong><p>{user.plan === 'pro' ? 'Pro plan' : 'Free plan'}</p></div><ChevronDown size={15} /></div><p className="nav-label">YOUR WORKSPACE</p><nav className="sidebar-nav"><button className={view === 'dashboard' || view === 'editor' ? 'active' : ''} onClick={() => setView('dashboard')}><LayoutDashboard size={18} />Overview</button><button className={view === 'settings' ? 'active' : ''} onClick={() => setView('settings')}><Settings size={18} />Business settings</button><button className={view === 'billing' ? 'active' : ''} onClick={() => setView('billing')}><CreditCard size={18} />Plan & billing</button></nav><div className="sidebar-bottom">{user.plan === 'free' && <div className="sidebar-upgrade"><span className="upgrade-sparkles"><Sparkles size={24} strokeWidth={1.4} /></span><strong>Good things are growing.</strong><p>{usage ? `${usage.used} of ${usage.limit ?? 3} free quotes used this month.` : '3 free quotes, every month.'}</p><div className="usage-track"><span style={{ width: `${Math.min((usage?.used ?? 0) / (usage?.limit || 3) * 100, 100)}%` }} /></div><button onClick={() => setView('billing')}>Explore Pro<ArrowRight size={15} /></button></div>}<div className="sidebar-user"><span className="user-avatar">{user.name.slice(0, 1).toUpperCase()}</span><div><strong>{user.name}</strong><span>{user.email}</span></div><button className="icon-button" title="Log out" aria-label="Log out" onClick={logout}><LogOut size={17} /></button></div></div></aside>
    <main className="app-main"><header className="workspace-header"><span>{view === 'dashboard' ? 'Overview' : view === 'editor' ? 'Your quotes' : view === 'settings' ? 'Business settings' : 'Plan & billing'}</span><div><span className="workspace-date">{new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</span><span className="header-divider" /><span className={`plan-pill ${user.plan === 'pro' ? 'pro' : ''}`}><Sparkles size={12} />{user.plan === 'pro' ? 'PRO PLAN' : 'FREE PLAN'}</span></div></header>{view === 'dashboard' && <Dashboard user={user} quotes={quotes} usage={usage} loading={loading} error={quotesError} refresh={refresh} onCreate={() => openEditor(null)} onEdit={openEditor} onDelete={setDeleting} onUpgrade={() => setView('billing')} />}{view === 'editor' && <QuoteEditor key={editorKey} user={user} initial={selected} onBack={() => { setView('dashboard'); refresh(); }} onSaved={saved} notify={notify} />}{view === 'settings' && <ProfileSettings user={user} onUpdated={setUser} notify={notify} />}{view === 'billing' && <Billing user={user} enabled={billingEnabled} usage={usage} notify={notify} />}</main>
    {toast && <div className={`toast ${toast.error ? 'error' : ''}`} role={toast.error ? 'alert' : 'status'}>{toast.error ? <X size={18} /> : <CheckCircle2 size={18} />}<span>{toast.message}</span><button className="icon-button" onClick={() => setToast(null)} aria-label="Dismiss notification"><X size={16} /></button></div>}{deleting && <Modal title="Delete this quote?" onClose={() => { if (!deleteBusy) setDeleting(null); }}><p className="muted">The quote for <strong>{deleting.clientName}</strong> and its shared link will be removed. This can’t be undone, and it won’t restore your monthly allowance.</p><div className="modal-actions"><Button className="btn-secondary" onClick={() => setDeleting(null)} disabled={deleteBusy}>Keep quote</Button><Button className="btn-danger" onClick={remove} loading={deleteBusy}><Trash2 size={16} />Delete quote</Button></div></Modal>}
  </div>;
}
