import { useState, type FormEvent } from 'react';
import { ArrowRight, Check, CheckCircle2, CreditCard, Loader2, ShieldCheck, Sparkles, X } from 'lucide-react';
import { api, dateLabel, errorMessage } from './api';
import type { Usage, User } from './types';
export default function Billing({ user, enabled, usage, notify }: { user: User; enabled: boolean; usage: Usage | null; notify: (message: string, error?: boolean) => void }) {
  const [showCheckout, setShowCheckout] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const params = new URLSearchParams(window.location.search);
  async function checkout(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError('');
    const form = event.currentTarget;
    const data = new FormData(form);
    try {
      const { url } = await api<{ url: string }>('/api/billing/checkout', { method: 'POST', body: JSON.stringify(Object.fromEntries(data)) });
      const target = new URL(url);
      if (target.protocol !== 'https:' || !['sandbox-cpp.iyzipay.com', 'cpp.iyzipay.com', 'checkout.iyzipay.com'].includes(target.hostname) || target.username || target.password || target.port) throw new Error('The payment link is unavailable. Please try again later.');
      form.reset(); window.location.assign(target.href);
    } catch (err) { form.reset(); setError(errorMessage(err)); notify(errorMessage(err), true); } finally { setBusy(false); }
  }
  return <div className="billing-page"><div className="page-heading"><div><p className="eyebrow">ROOM TO GROW</p><h1>A little investment. A polished impression.</h1><p className="muted">Start free. Make room for more clients when you’re ready.</p></div></div>{params.get('payment') === 'success' && <div className="info-banner"><CheckCircle2 size={20} /><p>{user.plan === 'pro' ? 'Payment confirmed. Your Pro access is ready.' : 'Checking your payment confirmation. Your plan updates when payment is verified; refresh shortly if it still shows Free.'}</p></div>}{params.get('payment') === 'failed' && <p className="form-error" role="alert">Payment wasn’t completed. Your existing plan stays active. You can try again when you’re ready.</p>}<div className="billing-grid"><section className="plan-card"><span className="eyebrow">FOR YOUR FIRST FEW YESES</span><h2>Free</h2><div className="plan-price">₺0<span>/ forever</span></div><p>A professional start, at your own pace.</p><ul><li><Check size={17} />3 new quotes every month</li><li><Check size={17} />Cleaning service templates</li><li><Check size={17} />Cost and profit margin helper</li><li><Check size={17} />Share links, online acceptance & PDF printing</li></ul><div className="current-plan">{user.plan === 'free' ? <><CheckCircle2 size={17} />Your current plan</> : 'Available when you need it'}</div></section><section className="plan-card pro-plan"><div className="pro-tag"><Sparkles size={13} />MORE ROOM TO GROW</div><span className="eyebrow">FOR A GROWING CLEANING BUSINESS</span><h2>Pro</h2><div className="plan-price">₺399<span>/ 30 days</span></div><p>Every inquiry deserves a great quote.</p><ul><li><Check size={17} />Unlimited new quotes</li><li><Check size={17} />Everything in Free</li><li><Check size={17} />30 days of prepaid Pro access</li><li><Check size={17} />No automatic renewal</li></ul>{user.plan === 'pro' && user.proUntil && <p className="pro-access-date">Pro access until {dateLabel(user.proUntil)}</p>}<button className="btn btn-primary full-width" disabled={!enabled} onClick={() => { setShowCheckout(true); setError(''); }}>{enabled ? user.plan === 'pro' ? 'Add 30 days of Pro' : 'Get 30 days of Pro' : 'Pro is coming soon'}<ArrowRight size={17} /></button>{!enabled && <p className="billing-unavailable">Payments aren’t available yet. Keep using your current plan.</p>}</section></div><section className="usage-card"><div><CreditCard size={23} /><div><h3>Your monthly quote allowance</h3><p>{user.plan === 'pro' ? 'You can create as many quotes as your business needs.' : `${usage?.used ?? 0} of ${usage?.limit ?? 3} quotes created this month. Your allowance resets each month.`}</p></div></div>{user.plan === 'free' && <p className="field-help">Deleting a quote doesn’t restore an allowance. Saved quotes remain available after a reset.</p>}</section><p className="billing-note">Pro pricing is in Turkish lira. Your clients’ quotes can use a different currency.</p>
    {showCheckout && enabled && <dialog ref={node => { if (node && !node.open) node.showModal(); }} onCancel={event => { event.preventDefault(); if (!busy) setShowCheckout(false); }} className="modal checkout-modal" aria-labelledby="checkout-title"><div className="modal-header"><h2 id="checkout-title">Your 30 days of Pro.</h2><button className="icon-button" disabled={busy} aria-label="Close payment form" onClick={() => setShowCheckout(false)}><X size={20} /></button></div><p className="muted">₺399, paid once. No automatic renewal. These billing details are required for your secure iyzico checkout.</p><form className="form-stack" onSubmit={checkout}><div className="form-two-columns"><label>First name<input name="name" required maxLength={80} defaultValue={user.name.split(' ')[0]} autoFocus autoComplete="given-name" /></label><label>Last name<input name="surname" required maxLength={80} defaultValue={user.name.split(' ').slice(1).join(' ')} autoComplete="family-name" /></label></div><label>Turkish mobile number<input name="phone" type="tel" required maxLength={25} defaultValue={user.phone} placeholder="+90 5xx xxx xx xx" autoComplete="tel" /></label><label>Turkish identity number<input name="identityNumber" inputMode="numeric" pattern="[1-9][0-9]{10}" required minLength={11} maxLength={11} autoComplete="off" placeholder="Your 11-digit identity number" /></label><label>Billing address<input name="address" required minLength={5} maxLength={500} autoComplete="street-address" /></label><label>City<input name="city" required minLength={2} maxLength={80} autoComplete="address-level2" /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="btn btn-primary full-width" disabled={busy} type="submit">{busy ? <Loader2 size={17} className="spin" /> : <ShieldCheck size={17} />}Continue to secure payment<ArrowRight size={16} /></button><p className="field-help">Card details are entered on iyzico’s secure payment page. Your identity number isn’t saved to your NeatQuote profile.</p></form></dialog>}
  </div>;
}
