import { useState } from 'react';
import { ArrowRight, ChevronDown, Lightbulb } from 'lucide-react';
import { money } from './api';
export default function PriceHelper({ currency, onUse, disabled }: { currency: string; onUse: (cents: number) => void; disabled: boolean }) {
  const [open, setOpen] = useState(false);
  const [hours, setHours] = useState(3);
  const [hourlyCost, setHourlyCost] = useState(currency === 'TRY' ? 250 : 16);
  const [supplies, setSupplies] = useState(currency === 'TRY' ? 150 : 10);
  const [travel, setTravel] = useState(currency === 'TRY' ? 150 : 10);
  const [margin, setMargin] = useState(30);
  const costs = Math.round((hours * hourlyCost + supplies + travel) * 100);
  const recommended = Math.round(costs / (1 - margin / 100));
  return <section className="price-helper"><button type="button" className="helper-toggle" onClick={() => setOpen(!open)} aria-expanded={open}><span className="helper-light"><Lightbulb size={20} /></span><span><strong>Price with confidence.</strong><span>A quick cost check before you send.</span></span><ChevronDown size={16} className={open ? 'helper-open' : ''} /></button>{open && <div className="helper-content"><p>Build an estimate around your time and costs. These planning figures stay off your client’s quote.</p><div className="helper-fields"><label>Estimated hours<input type="number" min="0" max="1000" step="0.25" value={hours} disabled={disabled} onChange={event => setHours(Math.max(0, Math.min(1000, Number(event.target.value))))} /></label><label>Hourly labor cost ({currency})<input type="number" min="0" max="100000" step="0.01" value={hourlyCost} disabled={disabled} onChange={event => setHourlyCost(Math.max(0, Math.min(100000, Number(event.target.value))))} /></label><label>Supplies ({currency})<input type="number" min="0" max="100000" step="0.01" value={supplies} disabled={disabled} onChange={event => setSupplies(Math.max(0, Math.min(100000, Number(event.target.value))))} /></label><label>Travel ({currency})<input type="number" min="0" max="100000" step="0.01" value={travel} disabled={disabled} onChange={event => setTravel(Math.max(0, Math.min(100000, Number(event.target.value))))} /></label><label>Target profit margin (%)<input type="number" min="0" max="90" step="1" value={margin} disabled={disabled} onChange={event => setMargin(Math.max(0, Math.min(90, Number(event.target.value))))} /></label></div><div className="helper-results"><div><span>Estimated break-even</span><strong>{money(costs, currency)}</strong></div><div><span>Suggested service price</span><strong>{money(recommended, currency)}</strong></div></div><p className="field-help">Suggested price = estimated costs ÷ (1 − target margin). Before tax and discount; discounts reduce your margin. Estimates depend on your inputs.</p><button type="button" className="btn btn-secondary full-width" disabled={disabled || recommended <= 0 || recommended > 10000000} onClick={() => onUse(recommended)}>Use recommended price<ArrowRight size={15} /></button><p className="field-help">Replaces your line items with one cleaning service covering the same scope.</p></div>}</section>;
}
